---
title: Condition of a Problem
author: Mathew Gluck
date: '2021-05-30'
slug: condition-of-a-problem
draft: true
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-05-30T20:42:17-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
bibliography: [../references.bib]
link-citations: true
---

Will discuss the condition of a problem. Model a problem as a function $f:\mathbb R^n\to \mathbb R^m$. Generally, the condition of a problem is (a linear approximation to) the amount by which the relative change in the output changes in response to a relative change in the input. Typically, we say the conditin of $f$ at $x$, so in the event that $x$ or $y = f(x)$ is zero, some modifications are made as the relative change is not defined. We assume throughout that $f$ is differentiable. 

# Warm up
We consider the case $m = n= 1$ and hence $f:\mathbb R\to \mathbb R$. Suppose the input $x\in \mathbb R\setminus\{0\}$ corresponds to output $y = f(x) \in \mathbb R\setminus\{0\}$. Suppose $x$ is perturbed by $h\in \mathbb R\setminus\{0\}$. The relative change in the output is
\begin{equation*}
    \frac{f(x + h) - f(x)}{f(x)}
    \approx \frac{f'(x)h}{f(x)}
    = \frac{x f'(x)}{f(x)}\cdot \frac{h}{x}, 
    \qquad x\neq 0, f(x)\neq 0. 
\end{equation*}
Thus, the relative change in the output is magnified by a factor of $x f'(x)/f(x)$. We define the *condition number of $f$ at $x$* by 
\begin{equation*}
    (\text{cond }f)(x) = \left| \frac{x f'(x)}{f(x)}\right|. 
\end{equation*}
Some mofifications need to be made if one of $x$ or $f(x)$ is zero. In short, the modifications are to use the aboslute error whenever the relative error is not defined. For example, if $x = 0$ and $f(x)\neq 0$ then we use the absolute perturbation $h$ in place of the relative perturbation $h/x$ to obtain 
\begin{equation*}
    (\text{cond }f)(0) = \left| \frac{f'(x)}{f(x)}\right|. 
\end{equation*}
Similarly, 
\begin{equation*}
\begin{split}
    (\text{cond }f)(x) 
        & = \left| xf'(x)\right| \qquad x\neq 0, f(x) = 0\\
    (\text{cond }f)(0)
        & = \left| f'(0)\right| \qquad x= 0, f(x) = 0\\
\end{split}
\end{equation*}



# General case
In general consider a differentiable function $f:\mathbb R^n\to \mathbb R^m$ with coordinate functions $f_i:\mathbb R^n\to \mathbb R$. The relative change in the output of $f_i$ in response to a perturbation $h$ in the $j^{\text{th}}$ coordinate is 
\begin{equation*}
    \frac{f_i(x + he_j) - f(x)}{f_i(x)}
    \approx \frac{h}{y_i}\frac{\partial f_i}{\partial x_j}(x)
    = \frac{x_j}{y_i}\frac{\partial f_i}{\partial x_j}(x) \cdot \frac{h}{x_j}
\end{equation*}
where $e_j$ is the $j^{\text{th}}$ standard basis vector in $\mathbb R^n$. We define 
\begin{equation}
    (\text{cond}_{ij} f)(x)
    = \left| \frac{x_j}{y_i}\frac{\partial f_i}{\partial x_j}(x)\right|
    = :\gamma_{ij}(x)
(\#eq:condition)
\end{equation}
with the appropriate modifications in the case that either of $f_i(x)$ or $x_j$ is zero. Arranging these numbers into a matrix $\Gamma(x) = (\gamma_{ij}(x))$ we define the condition number of $f$ at $x$ (relative to the norm $\|\cdot\|$) to be 
\begin{equation*}
    (\text{cond }f)(x) = \|\Gamma(x)\|. 
\end{equation*}

## A Less Refined (but Often Used) Approach

Denote the purturbation in the input $x$ by 
\begin{equation*}
    \Delta x = (\Delta x_1, \ldots, \Delta x_n)
\end{equation*}
and the relative perturbation as $\|\Delta x\|/\|x\|$. In this case, the relative change in the output in response to the perturbation $\Delta x$ is 
\begin{equation*}
\begin{split}
    \frac{\|f(x + \Delta x) - f(x)\|}{\|f(x)\|}
    & \approx \frac{\|J_f(x) \Delta x\|}{\|f(x)\|}\\
    & \leq \frac{\|x\|\|J_f(x)\|}{\|f(x)\|}\cdot \frac{\|\Delta x\|}{\|x\|}
\end{split}
\end{equation*}
where $J_f(x) \in M_{m\times n}(\mathbb R)$ is the Jacobian matrix of $f$ at $x$. Define the condition number by 
\begin{equation}
    (\widetilde{\text{cond }f})(x) 
    = \frac{\|x\|\|J_f(x)\|}{\|f(x)\|}. 
(\#eq:crudecondition)
\end{equation}
The following example is taken from @Gautschi2012. It illustrates that this approach is indeed less refined. 
````{example}
Let $f:\mathbb R^2\to \mathbb R^2$ be given by 
\begin{equation*}
    f(x_1, x_2)
    = \begin{bmatrix}
    x_1^{-1} + x_2^{-1}\\
    x_1^{-1}  - x_2^{-1}
    \end{bmatrix}
\end{equation*}
so that
\begin{equation*}
    J_f(x) = 
    \begin{bmatrix}
    -x_1^{-2} & -x_2^{-2}\\
    - x_1^{-1} & x_2^{-2}
    \end{bmatrix}
\end{equation*}
Using the notation above we have
\begin{equation*}
    \Gamma(x)
    = \begin{bmatrix}
    |x_2|/|x_1 + x_2| & |x_1|/|x_1 + x_2|\\
    |x_2|/|x_2 - x_1| & |x_1|/|x_2 - x_1|
    \end{bmatrix}
\end{equation*}
With respect to the (operator norm induced by the) norm $\|\cdot\|_\infty$ we have
\begin{equation*}
    \|\Gamma(x)\|_\infty = \max_i\sum_{j = 1}^2 |\gamma_{ij}(x)|. 
\end{equation*}
In particular, we have ill conditioning with respecto to $(\text{cond }f)$ whenever $x_1\approx x_2$ or $x_1 \approx - x_2$ and $|x_1|$ (and hence $|x_2|$) is not small. For example $x = (1, 1 \pm \delta)$ for $\delta > 0$ small. In fact by equivalence of norms in finite dimensions, this statment holds indpendently of which operator norm is used. 

On the other hand, using $1$-norms, we have
\begin{equation*}
    \|J_f(x)\|_1 = \frac{2}{x_1^2x_2^2}\max\{x_1^2, x_2^2\}
\end{equation*}
and therefore, when $x = (1, 1\pm \delta)$
\begin{equation*}
\begin{split}
    (\widetilde{\text{cond }f})(x)
    & = 2\frac{(|x_1| + |x_2|)\max\{x_1^2, x_2^2\}}{|x_1||x_2|(|x_1 + x_2| + |x_1 - x_2|)}\\
    & \approx 2
\end{split}
\end{equation*}
````
An example where $\widetilde{\text{cond }f}$ is used. 
````{example}
Let $A\in M_n(\mathbb R)$ be an invertible matrix and consider the matrix multiplicatio map $f:\mathbb R^n\to \mathbb R^n$ given by 
\begin{equation*}
    f(x) = Ax. 
\end{equation*}
In this case the commonly used notion of condition number is 
\begin{equation*}
    \kappa(A) := \|A\|\|A^{-1}\|. 
\end{equation*}
This notion does not perfectly coincide with either of \@ref(eq:condition) or \@ref(eq:crudecondition). However, in some sense it is the most naive notion of condition number that is uniform in $x$. It is easily derived from \@ref(eq:crudecondition), the imposition of uniformity in $x$ and the definition of the operator norm (of $A^{-1}$) as follows. For this $f$, the Jacobian matrix is $J_f(x) = A$ for all $x\in\mathbb R^n$. Therefore
\begin{equation*}
\begin{split}
    (\widetilde{\text{cond }f})(x)
    & = \frac{\|x\| \|A\|}{\|Ax\|}\\
    & = \frac{\|A^{-1}A x\| \|A\|}{\|Ax\|}\\
    & \leq \|A^{-1}\|\|A\|. 
\end{split}
\end{equation*}
````

# References
